#**Dataset import**

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

#**Dataset Basic Details**

In [ ]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [ ]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [ ]:
credits.head(1)['cast'].values

array(['[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'],
      dtype=object)

In [ ]:
credits.head(1)['crew'].values

array(['[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "depart

In [ ]:
movies.shape

(4803, 20)

In [ ]:
credits.shape

(4803, 4)

In [ ]:
movies = movies.merge(credits,on='title')

In [ ]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [ ]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 864.2+ KB

In [ ]:
# Useful columns according to our workflow:

# genres
# id
# keywords
# title
# overview
# cast
# crew

In [ ]:
movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [ ]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [ ]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4809 non-null   int64
 1   title     4809 non-null   object
 2   overview  4806 non-null   object
 3   genres    4809 non-null   object
 4   keywords  4809 non-null   object
 5   cast      4809 non-null   object
 6   crew      4809 non-null   object
dtypes: int64(1), object(6)
memory usage: 263.1+ KB

#**Data Preprocessing**

In [ ]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [ ]:
movies.dropna(inplace=True)

In [ ]:
movies.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [ ]:
movies.duplicated().sum()

np.int64(0)

In [ ]:
movies.iloc[1].genres

'[{"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 28, "name": "Action"}]'

In [ ]:
# The above output is a string of list of dictionay
# ['Adventure, 'Fantasy', Action', 'SciFi']
# We need to conver the data into this format.

In [ ]:
# convert into list of strings

import ast

In [ ]:
def convert(obj):
    L = []
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [ ]:
movies.dropna(inplace=True)

In [ ]:
movies['genres'] = movies['genres'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [ ]:
movies['keywords'] = movies['keywords'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [ ]:
def convert3(text):
    L = []
    counter = 0
    for i in ast.literal_eval(text):
        if counter < 3:
            L.append(i['name'])
        counter+=1
    return L

In [ ]:
movies['cast'] = movies['cast'].apply(convert)
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [ ]:
def fetch_director(text):
    L = []
    for i in ast.literal_eval(text):
        if i['job'] == 'Director':
            L.append(i['name'])
    return L

In [ ]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [ ]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton]

In [ ]:
movies['overview'][0]

# It is a String data type

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [ ]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

# The movies['overview'].apply(lambda x:x.split()) line. The split() method, when applied to a string, breaks that string into a list of substrings (words)
# based on whitespace by default. By using .apply(), I'm telling pandas to run this split() operation on each individual string in the 'overview' column.

movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton]

In [ ]:
movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ","")for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" ","")for i in x])
movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ","")for i in x])
movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" ","")for i in x])

In [ ]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux, Ralp...",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton]

In [ ]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [ ]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux, Ralp...",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [ ]:
new_df = movies[['movie_id','title','tags']]

In [ ]:
new_df

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui..."
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended..."
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi..."

In [ ]:
# To convert list of strings to Strings, use .join()

In [ ]:
new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

/tmp/ipykernel_2176/3089450492.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

In [ ]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [ ]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver StephenLang MichelleRodriguez GiovanniRibisi JoelDavidMoore CCHPounder WesStudi LazAlonso DileepRao MattGerald SeanAnthonyMoran JasonWhyte ScottLawrence KellyKilgour JamesPatrickPitt SeanPatrickMurphy PeterDillon KevinDorman KelsonHenderson DavidVanHorn JacobTomuri MichaelBlain-Rozgay JonCurry LukeHawker WoodySchultz PeterMensah SoniaYee JahnelCurfman IlramChoi KylaWarren LisaRoumain DebraWilson ChrisMala TaylorKibby JodieLandau JulieLamm CullenB.Madden JosephBradyMadden FrankieTorres AustinWilson SaraWilson TamicaWashington-Miller LucyBriant NathanMeister GerryBlair MatthewChamberlain PaulYates WrayWilson JamesGaylyn MelvinLenoClarkIII CarvonFutrell BrandonJelkes MicahMoch HanniyahMuhammad ChristopherNolen ChristaOliver AprilMarieThomas BravitaA.Threatt ColinBleasdale MikeBodnar MattClayton NicoleDionne JamieHarrison AllanHenry AnthonyIngruber AshleyJeffery DeanKnowsley JosephMika-Hunt TerryNotary KaiPantano LoganPithyou StuartPollock Raja GarethRuck RhianSheehan T.J.Storm JodieTaylor AliciaVela-Bailey RichardWhiteside NikieZambo JuleneRenee JamesCameron'

In [ ]:
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

/tmp/ipykernel_2176/3214958533.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

In [ ]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [ ]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4806 entries, 0 to 4808
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4806 non-null   int64
 1   title     4806 non-null   object
 2   tags      4806 non-null   object
dtypes: int64(1), object(2)
memory usage: 279.2+ KB

#**Text Vectorisation - using Bag of Words**

In [ ]:
# Convert text to vectors, the core idea is that the most similar movies vectors will be nearest to each other.

In [ ]:
# The Bag of Words (BoW) is a foundational Natural Language Processing (NLP) method that converts unstructured text into numerical data for machine learning algorithms.
# It ignores grammar and word order, determining importance entirely by how frequently words appear in a document/feature.
# We combine all the fetaures of all rows into a single cell and then take max_fetures = 5000 oe some other value.
# Then calculate the frequency of all the tags of a movie with respect to max_features.
# So, our data has 4806 movies, so each movie will have a vector of each feature. Hence, each movie will have 5000 vectors, which will create a 4806*5000 dimensional space.
# Stop words are common, high-frequency words (like "the", "and", "is", "in") filtered out during text processing and search engine indexing. They carry very little semantic meaning.

# We will use Scikit Learn Library for Text vectorisation, and then find the

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [ ]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [ ]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
vectors.shape

(4806, 5000)

In [ ]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
cv.get_feature_names_out()

array(['000', '10', '100', ..., 'zoo', 'zooeydeschanel', 'zoëkravitz'],
      dtype=object)

In [ ]:
print(cv.get_feature_names_out().tolist())

['000', '10', '100', '11', '12', '13', '14', '15', '16', '17', '18', '18th', '19', '1930s', '1940s', '1950s', '1960s', '1970s', '1980s', '19th', '19thcentury', '20', '20th', '24', '25', '30', '3d', '40', '50', '60', '60s', 'aaron', 'aaroneckhart', 'aarontaylor', 'aasifmandvi', 'abandoned', 'abducted', 'abigailbreslin', 'ability', 'able', 'abuse', 'abusive', 'academy', 'accept', 'accepts', 'access', 'accident', 'accidentally', 'accompanied', 'account', 'accountant', 'accused', 'ace', 'achieve', 'act', 'action', 'actions', 'activist', 'activities', 'actor', 'actors', 'actress', 'acts', 'actual', 'actually', 'adam', 'adambrody', 'adamgoldberg', 'adamlefevre', 'adams', 'adamsandler', 'adamscott', 'adamshankman', 'adaptation', 'addict', 'addicted', 'addiction', 'adewaleakinnuoye', 'adolescence', 'adopted', 'adoption', 'adrianmartinez', 'adrienbrody', 'adult', 'adultery', 'adulthood', 'adults', 'advantage', 'adventure', 'adventures', 'advertising', 'advice', 'affair', 'affection', 'affections', 'afghanistan', 'africa', 'african', 'aftercreditsstinger', 'afterlife', 'aftermath', 'agbaje', 'age', 'aged', 'agedifference', 'agency', 'agenda', 'agent', 'agents', 'aggressive', 'aging', 'ago', 'agree', 'agrees', 'ahead', 'aid', 'aidanquinn', 'aided', 'aids', 'ailing', 'air', 'airplane', 'airport', 'al', 'alanalda', 'alanarkin', 'alancumming', 'alanrickman', 'alantudyk', 'alaska', 'albert', 'albertbrooks', 'albertfinney', 'alcohol', 'alcoholic', 'alcoholism', 'alecbaldwin', 'alessandronivola', 'alex', 'alexandersiddig', 'alexapenavega', 'alexborstein', 'alexisbledel', 'alfredhitchcock', 'alfredmolina', 'alfrewoodard', 'ali', 'alice', 'alicedrummond', 'aliciawitt', 'alien', 'alieninvasion', 'alienlife', 'aliens', 'alike', 'alilarter', 'alive', 'allancorduner', 'allen', 'allencovert', 'alleong', 'alliance', 'allied', 'allies', 'allisonjanney', 'allow', 'allows', 'ally', 'alongside', 'alpacino', 'alter', 'alternate', 'alternative', 'alzheimer', 'amanda', 'amandapeet', 'amandaseyfried', 'amazing', 'ambassador', 'amberheard', 'ambition', 'ambitious', 'ambulance', 'ambush', 'america', 'american', 'americanfootball', 'americans', 'amidst', 'amnesia', 'amp', 'amy', 'amyadams', 'amypoehler', 'amyryan', 'amysedaris', 'amysmart', 'anagasteyer', 'analyst', 'anarchiccomedy', 'ancient', 'anderson', 'andiemacdowell', 'andreamartin', 'andrebraugher', 'andrew', 'andrewdaly', 'android', 'andy', 'andydick', 'andygarcía', 'andyrichter', 'andysamberg', 'andyserkis', 'angel', 'angelabassett', 'angeles', 'angelinajolie', 'angelo', 'anger', 'angry', 'animal', 'animalattack', 'animalhorror', 'animals', 'animated', 'animation', 'anjelicahuston', 'ann', 'anna', 'annafaris', 'annakendrick', 'annalevine', 'annapaquin', 'annasophiarobb', 'anndowd', 'anne', 'annebancroft', 'annefletcher', 'annehathaway', 'anneheche', 'annemoss', 'annettebening', 'annie', 'annikapergament', 'annual', 'answer', 'answers', 'ant', 'anthology', 'anthony', 'anthonyanderson', 'anthonyhopkins', 'anthonymackie', 'anthropomorphism', 'anti', 'antics', 'antihero', 'antonicorone', 'antoniobanderas', 'antonyelchin', 'apart', 'apartheid', 'apartment', 'ape', 'apes', 'apocalypse', 'apocalyptic', 'appear', 'appears', 'apple', 'apprentice', 'approaches', 'april', 'arab', 'archaeologist', 'architect', 'arctic', 'area', 'arena', 'arielwinter', 'arise', 'aristocrat', 'armed', 'arminmueller', 'arms', 'armstrong', 'army', 'arnold', 'arnoldschwarzenegger', 'arrest', 'arrested', 'arrival', 'arrive', 'arrives', 'arriving', 'art', 'arthur', 'arthurj', 'arthurtovey', 'artificialintelligence', 'artist', 'artists', 'arts', 'ashley', 'ashleyjudd', 'ashtonkutcher', 'asia', 'ask', 'asked', 'asks', 'aspirations', 'aspiring', 'assassin', 'assassination', 'assassins', 'assault', 'assigned', 'assignment', 'assistant', 'asteroid', 'astronaut', 'asylum', 'athlete', 'atomicbomb', 'attack', 'attacked', 'attacks', 'attempt', 'attempting', 'attempts', 'attending', 'attention', 'attitude', 'attorney', 'attraction', 'attractive', 'audience', 'audition', 'august', 'aunjanueellis', 'aunt', 'austin', 'australia', 'australian', 'author', 'authorities', 'authority', 'auto', 'avaacres', 'avenge', 'avoid', 'awaits', 'awakens', 'award', 'away', 'awry', 'azizansari', 'baby', 'bachelor', 'backdrop', 'bad', 'bahamas', 'bail', 'bailey', 'bailing', 'baker', 'balance', 'ball', 'ballet', 'band', 'banished', 'bank', 'banker', 'bankrobbery', 'baptiste', 'bar', 'barely', 'bargained', 'barn', 'barney', 'barry', 'barrylevinson', 'barrypepper', 'barryshabakahenley', 'base', 'baseball', 'based', 'basedoncomicbook', 'basedonnovel', 'basedonplay', 'basedonstagemusical', 'basedontrueevents', 'basedontruestory', 'basedontvseries', 'basedonvideogame', 'basedonyoungadultnovel', 'basement', 'basketball', 'batman', 'battle', 'battlefield', 'battles', 'battling', 'bay', 'beach', 'bear', 'bears', 'beast', 'beat', 'beautiful', 'beautifulwoman', 'beauty', 'beccasweitzer', 'becominganadult', 'bed', 'befriends', 'began', 'begin', 'beginning', 'begins', 'behavior', 'beliefs', 'believe', 'believed', 'believes', 'believing', 'bell', 'beloved', 'ben', 'benaffleck', 'benchaplin', 'benedictcumberbatch', 'benfoster', 'bengazzara', 'beniciodeltoro', 'benjamin', 'benjaminbratt', 'benkingsley', 'benmendelsohn', 'bennett', 'benstiller', 'bent', 'benwhishaw', 'berlin', 'bernardhill', 'bernardlee', 'berniemac', 'best', 'bestfriend', 'bet', 'beth', 'bethgrant', 'betrayal', 'bettemidler', 'better', 'betty', 'beverly', 'bible', 'big', 'biggest', 'biker', 'billcamp', 'billcobbs', 'billduke', 'billhader', 'billionaire', 'billmoseley', 'billmurray', 'billnighy', 'billnunn', 'billpaxton', 'billpullman', 'billy', 'billybobthornton', 'billyburke', 'billyconnolly', 'billycrudup', 'billycrystal', 'billydeewilliams', 'billyslaughter', 'billyzane', 'biography', 'bird', 'birth', 'birthday', 'bishop', 'bit', 'bite', 'bitter', 'bizarre', 'black', 'blackmail', 'blackpeople', 'blade', 'blake', 'blakeclark', 'blind', 'block', 'blonde', 'blood', 'bloodsplatter', 'bloodthirsty', 'bloody', 'blow', 'blue', 'blythedanner', 'board', 'boarding', 'boat', 'bob', 'bobbalaban', 'bobbergen', 'bobby', 'bobbycannavale', 'bobbyfarrelly', 'bobgunton', 'bobhoskins', 'bobstephenson', 'body', 'bodyguard', 'bokeemwoodbine', 'bold', 'bollywood', 'bomb', 'bombing', 'bond', 'bonniehunt', 'book', 'books', 'border', 'bored', 'boring', 'born', 'boss', 'boston', 'bound', 'boundaries', 'bounty', 'bountyhunter', 'box', 'boxer', 'boxing', 'boy', 'boydbanks', 'boydholbrook', 'boyfriend', 'boys', 'braddourif', 'bradgarrett', 'bradleycooper', 'bradleywhitford', 'bradpitt', 'bradwilliamhenke', 'brain', 'brave', 'bravery', 'brazil', 'brazilian', 'break', 'breaking', 'breaks', 'breckinmeyer', 'brendanfraser', 'brendangleeson', 'brendansextoniii', 'brentbriscoe', 'brentspiner', 'brettcullen', 'brettratner', 'brian', 'briancox', 'briandennehy', 'briandepalma', 'briandoyle', 'brianj', 'briano', 'bride', 'bridge', 'bridgettewilson', 'brief', 'brielarson', 'brien', 'brilliant', 'bring', 'bringing', 'brings', 'brink', 'britain', 'british', 'britishsecretservice', 'brittanymurphy', 'broadway', 'broke', 'broken', 'brooklyn', 'brooks', 'brothel', 'brother', 'brotherbrotherrelationship', 'brothers', 'brothersisterrelationship', 'brought', 'brown', 'bruce', 'brucecampbell', 'brucedern', 'brucegreenwood', 'brucemcgill', 'brucespence', 'brucewillis', 'brutal', 'brutality', 'brutally', 'bryan', 'bryancranston', 'bryansinger', 'brycedallashoward', 'buck', 'buddies', 'buddy', 'buddycomedy', 'budget', 'build', 'building', 'built', 'bully', 'bullying', 'bumbling', 'buried', 'burns', 'burtreynolds', 'bus', 'bush', 'business', 'businessman', 'busy', 'butler', 'buy', 'byrne', 'cabin', 'california', 'called', 'calls', 'callumkeithrennie', 'calvin', 'came', 'camera', 'cameras', 'cameron', 'cameronbright', 'camerondiaz', 'camgigandet', 'camp', 'campaign', 'campbell', 'camping', 'campus', 'canada', 'canadian', 'cancer', 'candidate', 'cannibal', 'capable', 'capitalism', 'captain', 'captive', 'capture', 'captured', 'captures', 'car', 'caraccident', 'caraseymour', 'carchase', 'carcrash', 'card', 'care', 'career', 'carefree', 'careymulligan', 'caribbean', 'carjourney', 'carl', 'carlagallo', 'carlagugino', 'carlosalazraqui', 'carmen', 'carmenelectra', 'carolineaaron', 'carolinegoodall', 'carolkane', 'carpenter', 'carrace', 'carrie', 'carriefisher', 'carry', 'carrying', 'cars', 'carter', 'cary', 'caryelwes', 'case', 'caseyaffleck', 'cash', 'casino', 'cast', 'castle', 'cat', 'catch', 'catches', 'cateblanchett', 'catherinekeener', 'catherineo', 'catherinezeta', 'cathey', 'catholic', 'catholicism', 'caught', 'cause', 'caused', 'causes', 'causing', 'cave', 'cedrictheentertainer', 'celebrate', 'celebrated', 'celebration', 'celebrity', 'celiaimrie', 'celiaweston', 'cellphone', 'cemetery', 'center', 'centered', 'centers', 'central', 'centuries', 'century', 'certain', 'chadmichaelmurray', 'chain', 'chainsaw', 'challenge', 'challenged', 'challenges', 'champion', 'championship', 'chance', 'chancekelly', 'change', 'changed', 'changes', 'changing', 'channingtatum', 'chaos', 'chapter', 'character', 'characters', 'charge', 'charged', 'charismatic', 'charles', 'charlesdance', 'charlesdurning', 'charlesnapier', 'charless', 'charlie', 'charliesheen', 'charlizetheron', 'charlotterampling', 'charltonheston', 'charm', 'charming', 'chase', 'chased', 'chazzpalminteri', 'cheating', 'cheechmarin', 'cheerleader', 'chef', 'chelcieross', 'chemical', 'cher', 'chevychase', 'chicago', 'chicken', 'chief', 'child', 'childabuse', 'childhood', 'children', 'chilling', 'chimcbride', 'china', 'chinese', 'chip', 'chiwetelejiofor', 'chloëgracemoretz', 'chloësevigny', 'chocolate', 'choice', 'choices', 'choose', 'chosen', 'chris', 'chriscolumbus', 'chriscooper', 'chrisellis', 'chrisevans', 'chrishemsworth', 'chrisklein', 'chrismessina', 'chrismiller', 'chriso', 'chrisparnell', 'chrispenn', 'chrispine', 'chrispratt', 'chrisrock', 'christ', 'christian', 'christianbale', 'christianity', 'christianslater', 'christinaapplegate', 'christinaricci', 'christinebaranski', 'christmas', 'christmasparty', 'christopher', 'christopherguest', 'christopherlambert', 'christopherlee', 'christopherlloyd', 'christophermcdonald', 'christophermeloni', 'christophermintz', 'christopherplummer', 'christopherwalken', 'christophwaltz', 'chronicle', 'chronicles', 'church', 'cia', 'ciaránhinds', 'cillianmurphy', 'circle', 'circumstances', 'circus', 'citizens', 'city', 'civil', 'civilization', 'civilwar', 'claim', 'claims', 'claire', 'clairedanes', 'claireforlani', 'clan', 'clancybrown', 'clark', 'clarkgregg', 'clash', 'class', 'classes', 'classic', 'classmate', 'classmates', 'claudevandamme', 'cleaduvall', 'clean', 'clear', 'clerk', 'client', 'cliffcurtis', 'cliftoncollinsjr', 'climbing', 'clinteastwood', 'clinthoward', 'cliveowen', 'clock', 'clone', 'clorisleachman', 'close', 'closer', 'club', 'clues', 'clutches', 'coach', 'coast', 'cocaine', 'code', 'cody', 'codycameron', 'cohen', 'cold', 'coldwar', 'cole', 'colehauser', 'colinfarrell', 'colinfirth', 'colinhanks', 'colinsalmon', 'collapse', 'colleague', 'colleagues', 'collect', 'collection', 'collector', 'colleencamp', 'college', 'collide', 'collins', 'collision', 'colmfeore', 'colmmeaney', 'colonel', 'colony', 'colorful', 'coma', 'combat', 'come', 'comeback', 'comedian', 'comedy', 'comes', 'comic', 'comics', 'coming', 'comingofage', 'comingout', 'command', 'commander', 'commercial', 'commit', 'commitment', 'committed', 'common', 'community', 'companion', 'company', 'compete', 'competing', 'competition', 'complete', 'completely', 'complex', 'complicated', 'complications', 'compton', 'computer', 'concert', 'condition', 'confidence', 'confident', 'conflict', 'confront', 'congress', 'conman', 'connected', 'connection', 'connell', 'connienielsen', 'connieray', 'connor', 'conquer', 'conradvernon', 'conscience', 'consequences', 'conspiracy', 'constantly', 'construction', 'contact', 'contest', 'continue', 'continues', 'contract', 'control', 'controversial', 'converge', 'convict', 'convicted', 'convince', 'convinced', 'convinces', 'cook', 'cooking', 'cool', 'cooper', 'cop', 'cope', 'cops', 'core', 'coreyburton', 'coreystoll', 'corporate', 'corporation', 'corpse', 'corrupt', 'corruption', 'cost', 'costume', 'couldn', 'count', 'country', 'countryside', 'couple', 'couples', 'courage', 'courageous', 'course', 'court', 'courtcase', 'courteneycox', 'courtroom', 'cousin', 'cover', 'covert', 'cowardliness', 'cowboy', 'crack', 'craig', 'craigrobinson', 'craigt', 'crash', 'crashes', 'crazy', 'create', 'created', 'creates', 'creation', 'creature', 'creatures', 'crew', 'crime', 'crimefighter', 'crimes', 'criminal', 'criminals', 'crisis', 'crispinglover', 'crocodile', 'cross', 'crossed', 'crosses', 'crown', 'cruel', 'cruelty', 'cruise', 'crush', 'crystal', 'crystallowe', 'cuba', 'cubagoodingjr', 'cult', 'cultfilm', 'cultural', 'culture', 'cultureclash', 'cure', 'current', 'curse', 'custody', 'cut', 'cyberpunk', 'cyborg', 'dad', 'daily', 'dakotafanning', 'daledickey', 'daledye', 'dan', 'danaivey', 'danaykroyd', 'dance', 'dancer', 'dancing', 'danecook', 'danger', 'dangerous', 'danhedaya', 'daniel', 'danielbrühl', 'danielcraig', 'danielday', 'danielmays', 'danielradcliffe', 'danielroebuck', 'danielvonbargen', 'danny', 'dannydevito', 'dannyglover', 'dannyhuston', 'dannymann', 'dannymcbride', 'dannytrejo', 'danpatrick', 'daring', 'dark', 'darkcomedy', 'darkest', 'darkness', 'darylhannah', 'darylsabara', 'dashmihok', 'date', 'dates', 'dating', 'daughter', 'daughters', 'dave', 'davechappelle', 'davefoley', 'davefranco', 'david', 'davidalangrier', 'davidarquette', 'davidbradley', 'davidcronenberg', 'davidcross', 'davidduchovny', 'davidfincher', 'davidharbour', 'davidhydepierce', 'davidjensen', 'davidkoechner', 'davidkrumholtz', 'davidmorse', 'davido', 'davidogdenstiers', 'davidoyelowo', 'davidpaymer', 'davidspade', 'davidstrathairn', 'davidthewlis', 'davidwarner', 'davidwarshofsky', 'davidwenham', 'davies', 'davis', 'daxshepard', 'day', 'days', 'dccomics', 'dea', 'dead', 'deadly', 'deaf', 'deal', 'dealer', 'dealers', 'dealing', 'deals', 'dean', 'deannorris', 'death', 'deathofafriend', 'deathpenalty', 'debimazar', 'debramonk', 'debt', 'debut', 'decade', 'decades', 'deceased', 'deceit', 'deception', 'decide', 'decided', 'decides', 'decision', 'decisions', 'dedicated', 'deeds', 'deep', 'deeper', 'deeply', 'deeproy', 'defeat', 'defend', 'defense', 'deliver', 'delroylindo', 'delusion', 'demands', 'demimoore', 'demon', 'demonicpossession', 'demons', 'deniserichards', 'denisleary', 'deniso', 'dennisdugan', 'dennisfarina', 'dennishaysbert', 'dennishopper', 'dennisquaid', 'dentist', 'denzelwashington', 'department', 'depressed', 'depression', 'deranged', 'deraydavis', 'derek', 'derekjacobi', 'derekluke', 'dermotmulroney', 'desert', 'deserted', 'designed', 'desire', 'desires', 'desmondllewelyn', 'despair', 'desperate', 'desperately', 'desperation', 'despite', 'destined', 'destiny', 'destroy', 'destroyed', 'destroying', 'destruction', 'details', 'detective', 'detectives', 'determine', 'determined', 'detroit', 'devastating', 'develop', 'developed', 'develops', 'device', 'devil', 'devoted', 'dexterfletcher', 'dialogue', 'diamond', 'diane', 'dianekeaton', 'dianekruger', 'dianelane', 'diannewiest', 'diary', 'dick', 'dickmiller', 'dictator', 'did', 'didn', 'die', 'died', 'diedrichbader', 'diego', 'dies', 'differences', 'different', 'difficult', 'dinameyer', 'diner', 'dinner', 'dinosaur', 'dinosaurs', 'directed', 'director', 'dirty', 'dirtycop', 'disabled', 'disappearance', 'disappeared', 'disappears', 'disaster', 'discover', 'discovered', 'discovering', 'discovers', 'discovery', 'disease', 'disfigurement', 'disgraced', 'disguise', 'disney', 'disorder', 'distant', 'district', 'disturbed', 'disturbing', 'divided', 'divorce', 'divorced', 'djimonhounsou', 'dna', 'doc', 'doctor', 'document', 'documentary', 'documents', 'does', 'doesn', 'dog', 'doing', 'doll', 'dollar', 'dolphin', 'dolphlundgren', 'domhnallgleeson', 'dominiccooper', 'dominicwest', 'don', 'donaldfaison', 'donaldsutherland', 'donallogue', 'doncheadle', 'donharvey', 'donnell', 'doomed', 'door', 'dorsey', 'double', 'doublelife', 'doubt', 'doug', 'dougjones', 'douglas', 'douglasm', 'dr', 'dracula', 'drag', 'dragon', 'drama', 'dramatic', 'drawn', 'draws', 'dream', 'dreams', 'drewbarrymore', 'drifter', 'drink', 'drinking', 'drive', 'driven', 'driver', 'drives', 'driving', 'drop', 'drug', 'drugabuse', 'drugaddiction', 'drugdealer', 'druglord', 'drugs', 'drugtraffic', 'drunk', 'drunken', 'du', 'dualidentity', 'dude', 'duel', 'duke', 'dumped', 'duo', 'duringcreditsstinger', 'dustinhoffman', 'dutch', 'dutton', 'duty', 'dwarves', 'dwaynejohnson', 'dwightyoakam', 'dying', 'dyinganddeath', 'dylan', 'dylanbaker', 'dylanmcdermott', 'dynamic', 'dynasty', 'dysfunctionalfamily', 'dystopia', 'dystopicfuture', 'eager', 'earlbrown', 'earlier', 'early', 'earn', 'earth', 'earthquake', 'east', 'easy', 'eating', 'eccentric', 'economic', 'economy', 'edbegleyjr', 'eddie', 'eddiegriffin', 'eddieizzard', 'eddiekayethomas', 'eddiemarsan', 'eddiemurphy', 'edgarramírez', 'edge', 'edharris', 'edhelms', 'ediemcclurg', 'editor', 'education', 'edward', 'edwardburns', 'edwardherrmann', 'edwardnorton', 'effort', 'efforts', 'egg', 'ego', 'egypt', 'el', 'eldenhenson', 'elderly', 'elements', 'eliaskoteas', 'elijahwood', 'eliroth', 'elisabethshue', 'elite', 'elizabeth', 'elizabethbanks', 'ella', 'ellefanning', 'ellenbarkin', 'ellenburstyn', 'ellenpage', 'elliottgould', 'ellis', 'elusive', 'elves', 'elvis', 'embark', 'embarks', 'embethdavidtz', 'emerge', 'emergency', 'emilehirsch', 'emily', 'emilyblunt', 'emilymortimer', 'emilywatson', 'emma', 'emmaroberts', 'emmastone', 'emmathompson', 'emmawatson', 'emmetwalsh', 'emotional', 'emotionally', 'emotions', 'emperor', 'empire', 'employee', 'employees', 'employer', 'encounter', 'encounters', 'end', 'ended', 'ending', 'ends', 'enemies', 'enemy', 'energy', 'enforcement', 'engaged', 'engineer', 'england', 'english', 'enigmatic', 'enlist', 'enlists', 'ensemblecast', 'ensues', 'entangled', 'enter', 'enterprise', 'enters', 'entire', 'entity', 'environment', 'epic', 'epidemic', 'era', 'eric', 'ericbana', 'ericbogosian', 'ericidle', 'ericroberts', 'ericstoltz', 'erin', 'erniehudson', 'eroticism', 'escapade', 'escape', 'escaped', 'escapes', 'escort', 'especially', 'espionage', 'estate', 'estranged', 'eternal', 'ethan', 'ethanembry', 'ethanhawke', 'ethansuplee', 'eugenelevy', 'europe', 'european', 'eva', 'evamendes', 'evanrachelwood', 'evans', 'eve', 'evening', 'event', 'events', 'eventually', 'evermore', 'everybody', 'everyday', 'evidence', 'evil', 'evolution', 'ewanmcgregor', 'ewenbremner', 'ex', 'exact', 'exactly', 'examines', 'exchange', 'exciting', 'execution', 'executive', 'exist', 'existence', 'exorcism', 'exotic', 'exoticisland', 'expectations', 'expected', 'expedition', 'experience', 'experienced', 'experiences', 'experiment', 'expert', 'explores', 'explosion', 'explosive', 'expose', 'exposed', 'exposes', 'extramaritalaffair', 'extraordinary', 'extraterrestrial', 'extraterrestrialtechnology', 'extreme', 'extremely', 'extremeviolence', 'eye', 'eyes', 'face', 'faced', 'faces', 'facility', 'facing', 'fact', 'factory', 'failed', 'failing', 'fails', 'fairy', 'fairytale', 'faith', 'faizonlove', 'fake', 'fall', 'fallen', 'falling', 'fallinginlove', 'falls', 'falseidentity', 'fame', 'families', 'family', 'familyrelationships', 'famkejanssen', 'famous', 'fan', 'fangvamp', 'fans', 'fantastic', 'fantasy', 'fantasyworld', 'far', 'farm', 'farmer', 'farmhouse', 'fascinated', 'fashion', 'fast', 'fat', 'fatal', 'fate', 'fateful', 'father', 'fatherdaughterrelationship', 'fathersonrelationship', 'favorite', 'fbi', 'fbiagent', 'fear', 'fears', 'feature', 'features', 'featuring', 'federation', 'feel', 'feeling', 'feelings', 'feels', 'feet', 'fellow', 'female', 'femalefriendship', 'femalenudity', 'femaleprotagonist', 'festival', 'fi', 'fiancé', 'fiancée', 'fiction', 'fic

In [ ]:
# Applying Stemming Technique

# The term "steaming" usually refers to text stemming in Natural Language Processing (NLP), or working with thermodynamics steam tables, or real-time data streaming.
# Stemming simplifies words down to their root form by stripping suffixes and prefixes (e.g., "running" becomes "run").

# The most common approach uses the NLTK library with either the Porter Stemmer or Snowball Stemmer

In [ ]:
!pip install nltk

Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.4.0)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.3)

In [ ]:
import nltk

In [ ]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [ ]:
def stem(text):
  y = []

  for i in text.split():
    y.append(ps.stem(i))

  string = " ".join(y)
  return string

In [ ]:
ps.stem('danced')

'danc'

In [ ]:
stem('In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver StephenLang MichelleRodriguez GiovanniRibisi JoelDavidMoore CCHPounder WesStudi LazAlonso DileepRao MattGerald SeanAnthonyMoran JasonWhyte ScottLawrence KellyKilgour JamesPatrickPitt SeanPatrickMurphy PeterDillon KevinDorman KelsonHenderson DavidVanHorn JacobTomuri MichaelBlain-Rozgay JonCurry LukeHawker WoodySchultz PeterMensah SoniaYee JahnelCurfman IlramChoi KylaWarren LisaRoumain DebraWilson ChrisMala TaylorKibby JodieLandau JulieLamm CullenB.Madden JosephBradyMadden FrankieTorres AustinWilson SaraWilson TamicaWashington-Miller LucyBriant NathanMeister GerryBlair MatthewChamberlain PaulYates WrayWilson JamesGaylyn MelvinLenoClarkIII CarvonFutrell BrandonJelkes MicahMoch HanniyahMuhammad ChristopherNolen ChristaOliver AprilMarieThomas BravitaA.Threatt ColinBleasdale MikeBodnar MattClayton NicoleDionne JamieHarrison AllanHenry AnthonyIngruber AshleyJeffery DeanKnowsley JosephMika-Hunt TerryNotary KaiPantano LoganPithyou StuartPollock Raja GarethRuck RhianSheehan T.J.Storm JodieTaylor AliciaVela-Bailey RichardWhiteside NikieZambo JuleneRenee JamesCameron')

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav stephenlang michellerodriguez giovanniribisi joeldavidmoor cchpounder wesstudi lazalonso dileeprao mattgerald seananthonymoran jasonwhyt scottlawr kellykilgour jamespatrickpitt seanpatrickmurphi peterdillon kevindorman kelsonhenderson davidvanhorn jacobtomuri michaelblain-rozgay joncurri lukehawk woodyschultz petermensah soniaye jahnelcurfman ilramchoi kylawarren lisaroumain debrawilson chrismala taylorkibbi jodielandau julielamm cullenb.madden josephbradymadden frankietorr austinwilson sarawilson tamicawashington-mil lucybri nathanmeist gerryblair matthewchamberlain paulyat wraywilson jamesgaylyn melvinlenoclarkiii carvonfutrel brandonjelk micahmoch hanniyahmuhammad christophernolen christaoliv aprilmariethoma bravitaa.threatt colinbleasdal mikebodnar mattclayton nicoledionn jamieharrison allanhenri anthonyingrub ashleyjefferi deanknowsley josephmika-hunt terrynotari kaipantano loganpithy stuartpollock raja garethruck rhiansheehan t.j.storm jodietaylor aliciavela-bailey richardwhitesid nikiezambo julenerene jamescameron'

In [ ]:
new_df['tags'] = new_df['tags'].apply(stem)

/tmp/ipykernel_2176/3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [ ]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bond’ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [ ]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [ ]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
vectors.shape

(4806, 5000)

In [ ]:
print(cv.get_feature_names_out().tolist())

['000', '007', '10', '100', '11', '12', '13', '14', '15', '16', '17', '18', '18th', '19', '1910', '1930', '1940', '1950', '1960', '1960s', '1970', '1970s', '1980', '1990', '19th', '19thcenturi', '20', '20th', '24', '25', '30', '3d', '40', '50', '60', '70', 'aaron', 'aaroneckhart', 'aarontaylor', 'aaronyoo', 'aasifmandvi', 'abandon', 'abduct', 'abigailbreslin', 'abil', 'abl', 'abov', 'abus', 'academi', 'accept', 'access', 'accid', 'accident', 'accompani', 'accomplish', 'account', 'accus', 'ace', 'achiev', 'act', 'action', 'activ', 'activist', 'actor', 'actress', 'actual', 'adam', 'adambrodi', 'adamgoldberg', 'adamlefevr', 'adamsandl', 'adamscott', 'adamshankman', 'adapt', 'add', 'addict', 'adewaleakinnuoye', 'adjust', 'admir', 'admit', 'adolesc', 'adopt', 'ador', 'adrianmartinez', 'adrienbrodi', 'adult', 'adulteri', 'adulthood', 'advanc', 'adventur', 'adventure', 'advertis', 'advic', 'affair', 'affect', 'afghanistan', 'africa', 'african', 'aftercreditssting', 'afterlif', 'aftermath', 'ag', 'agbaj', 'age', 'agediffer', 'agency', 'agenda', 'agent', 'aggress', 'ago', 'agre', 'ahead', 'aid', 'aidanquinn', 'ail', 'aim', 'air', 'airplan', 'airport', 'al', 'alabama', 'alanalda', 'alanarkin', 'alancum', 'alanrickman', 'alantudyk', 'alaska', 'albert', 'albertbrook', 'albertfinney', 'alcohol', 'alecbaldwin', 'alessandronivola', 'alex', 'alexandersiddig', 'alexapenavega', 'alexborstein', 'alexisbledel', 'alfredhitchcock', 'alfredmolina', 'alfrewoodard', 'ali', 'alic', 'alice', 'alicebraga', 'alicedrummond', 'aliciasilverston', 'aliciawitt', 'alien', 'alieninvas', 'alienlife', 'alilart', 'aliv', 'alive', 'allancordun', 'allen', 'allencovert', 'alleong', 'alli', 'allianc', 'allisonjanney', 'allow', 'alon', 'alongsid', 'alpacino', 'alreadi', 'alter', 'altern', 'alunarmstrong', 'alway', 'alzheimer', 'amanda', 'amandapeet', 'amandaseyfri', 'amateur', 'amaz', 'ambassador', 'amberheard', 'ambervalletta', 'ambit', 'ambiti', 'ambul', 'ambush', 'america', 'american', 'americanfootbal', 'amid', 'amidst', 'amnesia', 'amp', 'amus', 'amyadam', 'amypoehl', 'amyryan', 'amysedari', 'amysmart', 'anagastey', 'analyst', 'anarchiccomedi', 'ancient', 'ancientrom', 'ancientworld', 'anderson', 'andi', 'andiemacdowel', 'andreamartin', 'andrebraugh', 'andrew', 'andrewdali', 'android', 'andydick', 'andygarcía', 'andyricht', 'andysamberg', 'andyserki', 'angel', 'angelabassett', 'angeles', 'angelinajoli', 'angelo', 'anger', 'angle', 'angri', 'ani', 'anim', 'animalattack', 'animalhorror', 'anjelicahuston', 'ann', 'anna', 'annafari', 'annakendrick', 'annalevin', 'annapaquin', 'annasophiarobb', 'anndowd', 'anne', 'annebancroft', 'annefletch', 'annehathaway', 'annehech', 'annemoss', 'annetteben', 'anni', 'annikaperga', 'announc', 'annual', 'anonym', 'anoth', 'answer', 'ant', 'antholog', 'anthoni', 'anthonyanderson', 'anthonyhopkin', 'anthonylapaglia', 'anthonymacki', 'anthropomorph', 'anti', 'antihero', 'antonicoron', 'antoniobandera', 'antonyelchin', 'anyon', 'anyth', 'apart', 'apartheid', 'apartment', 'ape', 'apocalyps', 'apocalypt', 'appar', 'appear', 'appoint', 'appreci', 'apprentic', 'approach', 'april', 'arab', 'archaeologist', 'architect', 'arctic', 'area', 'arena', 'arielwint', 'aris', 'aristocrat', 'arm', 'armi', 'arminmueller', 'armsdeal', 'armstrong', 'army', 'arnold', 'arnoldschwarzenegg', 'arrang', 'arrest', 'arriv', 'art', 'arthur', 'arthurj', 'arthurtovey', 'artificialintellig', 'artist', 'ash', 'ashley', 'ashleyjudd', 'ashtonkutch', 'asia', 'ask', 'aspir', 'assassin', 'assault', 'assign', 'assist', 'assistant', 'associ', 'assum', 'asteroid', 'astronaut', 'asylum', 'athlet', 'atomicbomb', 'attack', 'attempt', 'attend', 'attent', 'attitud', 'attorney', 'attract', 'audienc', 'audit', 'august', 'aunjanueelli', 'aunt', 'austin', 'australia', 'australian', 'author', 'autism', 'auto', 'avaacr', 'aveng', 'avoid', 'await', 'awaken', 'award', 'away', 'awkward', 'awri', 'awry', 'azizansari', 'babe', 'babi', 'baby', 'bachelor', 'backdrop', 'background', 'bad', 'bag', 'bahama', 'bail', 'bailey', 'balanc', 'ball', 'ballet', 'band', 'banish', 'bank', 'banker', 'bankrobberi', 'baptist', 'bar', 'bare', 'bargain', 'barn', 'barney', 'barri', 'barrylevinson', 'barrypepp', 'barryshabakahenley', 'bas', 'base', 'basebal', 'basedoncomicbook', 'basedonnovel', 'basedonplay', 'basedonstagemus', 'basedontrueev', 'basedontruestori', 'basedontvseri', 'basedonvideogam', 'basedonyoungadultnovel', 'basement', 'basketbal', 'batman', 'battl', 'battle', 'battlefield', 'bay', 'bdwong', 'beach', 'bear', 'beast', 'beat', 'beaubridg', 'beauti', 'beautiful', 'beautifulwoman', 'beauty', 'becam', 'becaus', 'beccasweitz', 'becom', 'becominganadult', 'bed', 'bedroom', 'beer', 'befor', 'befriend', 'began', 'begin', 'behavior', 'belief', 'believ', 'bell', 'bella', 'belong', 'belov', 'ben', 'benaffleck', 'benchaplin', 'bend', 'benedictcumberbatch', 'benedictwong', 'benfost', 'bengazzara', 'beniciodeltoro', 'benjamin', 'benjaminbratt', 'benkingsley', 'benmendelsohn', 'bennett', 'benstil', 'bent', 'benwhishaw', 'berlin', 'bernardhil', 'bernardle', 'berniemac', 'best', 'bestfriend', 'bet', 'beth', 'bethgrant', 'betray', 'bettemidl', 'better', 'betti', 'beverli', 'bibl', 'big', 'biggest', 'biker', 'billcamp', 'billcobb', 'billduk', 'billhad', 'billi', 'billionair', 'billmoseley', 'billmurray', 'billnighi', 'billnunn', 'billpaxton', 'billpullman', 'billybobthornton', 'billyburk', 'billyconnolli', 'billycrudup', 'billycryst', 'billydeewilliam', 'billyslaught', 'billyzan', 'biographi', 'bird', 'birth', 'birthday', 'bisexu', 'bishop', 'bit', 'bite', 'bitter', 'bizarr', 'black', 'blackmail', 'blackpeopl', 'blade', 'blakeclark', 'blame', 'blend', 'blind', 'bliss', 'block', 'blond', 'blood', 'bloodi', 'bloodsplatt', 'bloodthirsti', 'blow', 'blue', 'blythedann', 'board', 'boardingschool', 'boat', 'bob', 'bobbalaban', 'bobbergen', 'bobbi', 'bobbycannaval', 'bobbyfarrelli', 'bobbymoynihan', 'bobclendenin', 'bobgunton', 'bobhoskin', 'bobodenkirk', 'bobstephenson', 'bodi', 'body', 'bodyguard', 'bokeemwoodbin', 'bold', 'bollywood', 'bomb', 'bond', 'bone', 'bonniehunt', 'book', 'border', 'bore', 'boredom', 'born', 'boss', 'boston', 'bound', 'bounti', 'bountyhunt', 'box', 'boxer', 'boy', 'boydbank', 'boydholbrook', 'boyfriend', 'boys', 'braddourif', 'bradgarrett', 'bradleycoop', 'bradleywhitford', 'bradpitt', 'bradwilliamhenk', 'brain', 'brand', 'brave', 'braveri', 'brazil', 'brazilian', 'break', 'breckinmey', 'brendanfras', 'brendangleeson', 'brendansextoniii', 'brentbrisco', 'brentspin', 'brettcullen', 'brettratn', 'brian', 'briancox', 'briandennehi', 'briandepalma', 'briandoyle', 'brianj', 'briano', 'bride', 'bridg', 'bridgettewilson', 'brief', 'brielarson', 'brien', 'brilliant', 'bring', 'brink', 'britain', 'british', 'britishsecretservic', 'brittanymurphi', 'broadway', 'broke', 'broken', 'brook', 'brooklyn', 'brothel', 'brother', 'brotherbrotherrelationship', 'brothers', 'brothersisterrelationship', 'brought', 'brown', 'bruce', 'brucecampbel', 'brucedern', 'brucegreenwood', 'brucemcgil', 'brucesp', 'brucewilli', 'brutal', 'bryan', 'bryancranston', 'bryansing', 'brycedallashoward', 'bu', 'buck', 'bud', 'buddi', 'buddy', 'buddycomedi', 'budget', 'build', 'building', 'built', 'bullet', 'bulli', 'bumbl', 'burglar', 'buri', 'burn', 'burtreynold', 'bush', 'busi', 'business', 'businessman', 'bust', 'butler', 'buy', 'byrn', 'cabin', 'caesar', 'cage', 'cairo', 'cal', 'california', 'callahan', 'callumkeithrenni', 'calvin', 'camcord', 'came', 'camera', 'cameraman', 'cameron', 'cameronbright', 'camerondiaz', 'camgigandet', 'camp', 'campaign', 'campbel', 'campbellscott', 'campu', 'canada', 'canadian', 'cancer', 'candid', 'cannib', 'capabl', 'capit', 'captain', 'captiv', 'captur', 'car', 'caraccid', 'caraseymour', 'carchas', 'carcrash', 'card', 'care', 'career', 'careymulligan', 'caribbean', 'carjourney', 'carl', 'carlagallo', 'carlagugino', 'carlo', 'carlosalazraqui', 'carmen', 'carmenelectra', 'carol', 'carolineaaron', 'carolinegoodal', 'carolkan', 'carrac', 'carri', 'carrie', 'carriefish', 'carter', 'cary', 'caryelw', 'case', 'caseyaffleck', 'cash', 'casino', 'cast', 'castl', 'cat', 'cataclysm', 'catastroph', 'catch', 'cateblanchett', 'catherinekeen', 'catherineo', 'catherinezeta', 'cathey', 'cathol', 'catholic', 'caught', 'caus', 'cave', 'cedrictheentertain', 'celebr', 'celiaimri', 'celiaweston', 'cellphon', 'cemeteri', 'center', 'central', 'centuri', 'centuries', 'century', 'certain', 'chadmichaelmurray', 'chain', 'chainsaw', 'challeng', 'champion', 'championship', 'chanc', 'chance', 'chancekelli', 'chang', 'channingtatum', 'chao', 'chaos', 'chapter', 'charact', 'character', 'characters', 'charg', 'charismat', 'charl', 'charlesd', 'charlesdurn', 'charlesnapi', 'charless', 'charli', 'charlie', 'charliesheen', 'charlizetheron', 'charlotterampl', 'charltonheston', 'charm', 'chase', 'chazzpalminteri', 'cheat', 'cheechmarin', 'cheerlead', 'chef', 'chelcieross', 'chemic', 'cher', 'cherryjon', 'chevychas', 'chicago', 'chicken', 'chief', 'child', 'childabus', 'childhood', 'children', 'chill', 'chimcbrid', 'china', 'chines', 'chip', 'chiwetelejiofor', 'chloëgracemoretz', 'chloësevigni', 'chocol', 'choic', 'choos', 'chosen', 'chowyun', 'chri', 'chrisbauer', 'chrisbrown', 'chriscolumbu', 'chriscoop', 'chriselli', 'chrisevan', 'chrishemsworth', 'chriskattan', 'chrisklein', 'chrismessina', 'chrismil', 'chrismulkey', 'chriso', 'chrisparnel', 'chrispenn', 'chrispin', 'chrispratt', 'chrisrock', 'christ', 'christian', 'christianbal', 'christianslat', 'christinaappleg', 'christinaricci', 'christinebaranski', 'christma', 'christmas', 'christmasparti', 'christoph', 'christopherguest', 'christopherlambert', 'christopherle', 'christopherlloyd', 'christophermcdonald', 'christophermeloni', 'christophermintz', 'christopherplumm', 'christopherwalken', 'christophwaltz', 'chronicl', 'church', 'cia', 'ciaránhind', 'cillianmurphi', 'cinema', 'circl', 'circu', 'circuit', 'circumst', 'citi', 'citizen', 'city', 'civil', 'civilian', 'civilwar', 'claim', 'clair', 'clairedan', 'claireforlani', 'clan', 'clancybrown', 'clark', 'clarkduk', 'clarkgregg', 'clash', 'class', 'classic', 'classmat', 'classroom', 'claudevandamm', 'cleaduval', 'clean', 'clear', 'clerk', 'client', 'cliffcurti', 'cliftoncollinsjr', 'climat', 'climb', 'clinteastwood', 'clinthoward', 'cliveowen', 'clock', 'clone', 'clorisleachman', 'close', 'closer', 'clown', 'club', 'clue', 'coach', 'coast', 'cocain', 'code', 'codycameron', 'cohen', 'col', 'cold', 'coldwar', 'cole', 'colehaus', 'colinfarrel', 'colinfirth', 'colinhank', 'colinsalmon', 'collaps', 'colleagu', 'collect', 'collector', 'colleencamp', 'colleg', 'college', 'collid', 'collin', 'collis', 'colmfeor', 'colmmeaney', 'colonel', 'coloni', 'color', 'coma', 'combat', 'combin', 'come', 'comeback', 'comedi', 'comedian', 'comedy', 'comfort', 'comic', 'coming', 'comingofag', 'comingout', 'command', 'commando', 'commerci', 'commit', 'common', 'commun', 'compani', 'companion', 'company', 'compet', 'competit', 'competition', 'complet', 'complex', 'complic', 'compos', 'compton', 'comput', 'conan', 'concern', 'concert', 'condit', 'confess', 'confid', 'conflict', 'confront', 'confus', 'congress', 'conman', 'connect', 'connel', 'connienielsen', 'connieray', 'connor', 'conquer', 'conradvernon', 'consequ', 'consequences', 'consid', 'conspir', 'conspiraci', 'constantli', 'construct', 'consum', 'contact', 'contain', 'contemporari', 'contend', 'contest', 'continu', 'contract', 'control', 'controversi', 'convent', 'convict', 'convinc', 'cook', 'cool', 'cooper', 'cop', 'cope', 'corbinbleu', 'core', 'coreyburton', 'coreyfeldman', 'coreyjohnson', 'coreystol', 'corner', 'corpor', 'corps', 'corrupt', 'cost', 'costasmandylor', 'costum', 'couldn', 'count', 'countri', 'country', 'countrysid', 'coup', 'coupl', 'couple', 'courag', 'cours', 'court', 'courtcas', 'courteneycox', 'courtneyb', 'courtroom', 'cousin', 'cover', 'covert', 'cowardli', 'cowboy', 'crack', 'craft', 'craig', 'craigbierko', 'craigrobinson', 'craigt', 'crash', 'crazi', 'creat', 'creation', 'creativ', 'creator', 'creatur', 'creatures', 'credit', 'crew', 'crime', 'crimefight', 'crimin', 'criminal', 'criminals', 'crisi', 'crisis', 'crispinglov', 'critic', 'crocodil', 'crook', 'cross', 'crowd', 'crown', 'cruel', 'cruis', 'crusad', 'crush', 'crystal', 'crystallow', 'cuba', 'cubagoodingjr', 'cult', 'cultfilm', 'cultur', 'cultureclash', 'cup', 'cure', 'current', 'curs', 'curse', 'curtisarmstrong', 'custodi', 'custom', 'cut', 'cyberpunk', 'cyborg', 'cynic', 'dad', 'daili', 'dakotafan', 'daledickey', 'daledy', 'damag', 'dan', 'danaivey', 'danaykroyd', 'danc', 'dancer', 'danecook', 'danger', 'danhedaya', 'daniel', 'danielbrühl', 'danielcraig', 'danielday', 'danielmay', 'danielradcliff', 'danielroebuck', 'danielvonbargen', 'danni', 'danny', 'dannydevito', 'dannyglov', 'dannyhuston', 'dannymann', 'dannymcbrid', 'dannytrejo', 'danpatrick', 'dare', 'dark', 'darkcomedi', 'darkest', 'darylhannah', 'darylsabara', 'dashmihok', 'date', 'daughter', 'dave', 'davechappel', 'davefoley', 'davefranco', 'davi', 'david', 'davidalangri', 'davidarquett', 'davidbow', 'davidbradley', 'davidcronenberg', 'davidcross', 'davidduchovni', 'davidfinch', 'davidharbour', 'davidhydepierc', 'davidjensen', 'davidkoechn', 'davidkrumholtz', 'davidmors', 'davido', 'davidogdensti', 'davidoyelowo', 'davidpatrickkelli', 'davidpaym', 'davidprov', 'davidschwimm', 'davidspad', 'davidstern', 'davidstrathairn', 'davidthewli', 'davidwarn', 'davidwarshofski', 'davidwenham', 'davidzuck', 'daxshepard', 'day', 'days', 'dccomic', 'dea', 'dead', 'deadli', 'deaf', 'deal', 'dealer', 'dean', 'deannorri', 'death', 'deathofafriend', 'deathpenalti', 'debimazar', 'deborahkaraung', 'debramess', 'debramonk', 'debt', 'debut', 'decad', 'decapit', 'deceas', 'deceit', 'decept', 'decid', 'decis', 'declar', 'dedic', 'deed', 'deep', 'deeper', 'deepli', 'deeproy', 'defeat', 'defend', 'defens', 'defi', 'deirdreo', 'del', 'deliv', 'delroylindo', 'delus', 'demand', 'demimoor', 'demon', 'demonicpossess', 'demons', 'deniserichard', 'denisleari', 'deniso', 'dennisdugan', 'dennisfarina', 'dennishaysbert', 'dennishopp', 'dennisquaid', 'dentist', 'denzelwashington', 'depart', 'depict', 'depress', 'deputi', 'derang', 'deraydavi', 'derek', 'derekjacobi', 'derekluk', 'dermotmulroney', 'descend', 'desert', 'design', 'desir', 'desmondllewelyn', 'desol', 'despair', 'desper', 'despit', 'destin', 'destini', 'destroy', 'destruct', 'destruction', 'detect', 'detective', 'determin', 'detroit', 'devast', 'develop', 'devic', 'devil', 'devis', 'devot', 'dexterfletch', 'diamond', 'dianekeaton', 'dianekrug', 'dianelan', 'diannewiest', 'diari', 'dick', 'dickmil', 'dictat', 'did', 'didn', 'die', 'diedrichbad', 'diego', 'diegoluna', 'dies', 'differ', 'difficult', 'dig', 'dinamey', 'diner', 'dinner', 'dinosaur', 'direct', 'director', 'dirti', 'dirtycop', 'disappear', 'disast', 'disaster', 'discov', 'discoveri', 'diseas', 'disease', 'disfigur', 'disgrac', 'disguis', 'disney', 'disord', 'dispatch', 'distant', 'district', 'disturb', 'dive', 'divid', 'divorc', 'divorce', 'djimonhouns', 'dna', 'doc', 'doctor', 'document', 'documentari', 'doe', 'doesn', 'dog', 'doll', 'dollar', 'dolphin', 'dolphlundgren', 'domest', 'domhnallgleeson', 'domin', 'dominiccoop', 'dominicwest', 'don', 'donaldfaison', 'donaldpleas', 'donaldsutherland', 'donallogu', 'doncheadl', 'donharvey', 'donnel', 'doom', 'door', 'dorsey', 'doubl', 'double', 'doublelif', 'doubt', 'doug', 'dougjon', 'douglasm', 'dr', 'dracula', 'drag', 'dragon', 'drama', 'dramat', 'draw', 'drawn', 'dread', 'dream', 'dreams', 'dress', 'drewbarrymor', 'drifter', 'drink', 'drive', 'driven', 'driver', 'drop', 'drown', 'drug', 'drugabus', 'drugaddict', 'drugdeal', 'druglord', 'drugs', 'drugtraff', 'drunk', 'drunken', 'du', 'dualident', 'dude', 'duel', 'duke', 'dump', 'duo', 'dure', 'duringcreditssting', 'dustinhoffman', 'dutch', 'duti', 'dutton', 'dwaynejohnson', 'dwightyoakam', 'dyinganddeath', 'dylan', 'dylanbak', 'dylanmcdermott', 'dynam', 'dysfunctionalfamili', 'dystopia', 'dystopicfutur', 'eager', 'earlbrown', 'earli', 'earlier', 'earn', 'earth', 'earthquak', 'easi', 'east', 'eat', 'eccentr', 'econom', 'economi', 'edbegleyjr', 'eddi', 'eddie', 'eddiegriffin', 'eddieizzard', 'eddiekayethoma', 'eddiemarsan', 'eddiemurphi', 'edg', 'edgarramírez', 'edharri', 'edhelm', 'ediemcclurg', 'editor', 'edlaut', 'educ', 'edward', 'edwardburn', 'edwardfox', 'edwardherrmann', 'edwardjamesolmo', 'edwardnorton', 'effect', 'effort', 'egg', 'ego', 'egypt', 'el', 'elabor', 'eldenhenson', 'elderli', 'elect', 'element', 'elev', 'eliaskotea', 'elijahwood', 'elimin', 'eliroth', 'elisabethshu', 'elit', 'elizabeth', 'elizabethbank', 'ella', 'ellefan', 'ellenbarkin', 'ellenburstyn', 'ellenpag', 'elli', 'elliottgould', 'els', 'elud', 'elus', 'elv', 'elvi', 'embark', 'embethdavidtz', 'embroil', 'emerg', 'emilehirsch', 'emili', 'emilyblunt', 'emilymortim', 'emilywatson', 'emma', 'emmarobert', 'emmaston', 'emmathompson', 'emmawatson', 'emmetwalsh', 'emot', 'emperor', 'empire', 'employ', 'employe', 'encount', 'encourag', 'end', 'enemi', 'enemies', 'enemy', 'energi', 'enforc', 'engag', 'engin', 'england', 'english', 'enigmat', 'enjoy', 'enlist', 'ensemblecast', 'ensu', 'ensues', 'entangl', 'enter', 'enterpris', 'entertain', 'entir', 'entiti', 'environment', 'epic', 'epidem', 'episod', 'equal', 'era', 'eric', 'ericbana', 'ericbogosian', 'ericidl', 'ericrobert', 'ericstoltz', 'erin', 'ernest', 'ernestborgnin', 'erniehudson', 'erotic', 'erupt', 'escap', 'escapad', 'escape', 'escort', 'especi', 'espionag', 'establish', 'estat', 'estrang', 'etern', 'ethan', 'ethanembri', 'ethanhawk', 'ethansuple', 'ethic', 'eugenelevi', 'europ', 'european', 'eva', 'evacu', 'evad', 'evamend', 'evanrachelwood', 'eve', 'event', 'events', 'eventu', 'everi', 'evermor', 'everybodi', 'everyday', 'everyon', 'everyth', 'evid', 'evil', 'evolv', 'ewanmcgregor', 'ewenbremn', 'ex', 'exact', 'exactli', 'examin', 'exchang', 'excit', 'execut', 'exist', 'existence', 'existenti', 'exorc', 'exot', 'exoticisland', 'expect', 'expected', 'expedit', 'experi', 'experienc', 'expert', 'explain', 'explod', 'exploit', 'explor', 'explos', 'expos', 'extramaritalaffair', 'extraordinari', 'extraterrestri', 'extraterrestrialtechnolog', 'extrem', 'extremeviol', 'eye', 'fac', 'face', 'fact', 'factori', 'fade', 'fail', 'fairi', 'fairytal', 'faith', 'faizonlov', 'fake', 'fall', 'fallen', 'fallinginlov', 'falseident', 'fame', 'famili', 'family', 'familyrelationship', 'famkejanssen', 'famou', 'fan', 'fangvamp', 'fantasi', 'fantast', 'fantasyworld', 'far', 'farm', 'farmer', 'fascin', 'fashion', 'fast', 'fat', 'fatal', 'fate', 'father', 'fatherdaughterrelationship', 'fathersonrelationship', 'favor', 'favorit', 'fbi', 'fbiagent', 'fear', 'featur', 'feder', 'feel', 'feet', 'fellow', 'femal', 'female', 'femalefriendship', 'femalenud', 'femaleprotagonist', 'fend', 'ferguson', 'festiv', 'fi', 'fiancé', 'fiction', 'fictionalplac', 'field', 'fierc', 'fight', 'fighter', 'figur', 'file', 'film', 'filmmak', 'filmproduc', 'films', 'final', 'financi', 'finish', 'firm', 'fish', 'fisherman', 'fishersteven', 'fistfight', 'fit', 'fix', 'flashback', 'flee', 'flesh', 'fli', 'flight', 'flirt', 'flood', 'florida', 'flower', 'flynn', 'focu', 'focus', 'foil', 'folk', 'follow', 'food', 'foot', 'footag', 'footbal', 'footchas', 'forbidden', 'forbiddenlov', 'forc', 'force', 'forces', 'ford', 'foreign', 'forest', 'forestwhitak', 'forev', 'forever', 'forg', 'forget', 'forgiv', 'form', 'formid', 'formula', 'fort', 'fortun', 'fortune', 'forward', 'foster', 'fought', 'foundfootag', 'fourth', 'fox', 'frame', 'franc', 'france', 'francesconroy', 'francesdelatour', 'francesfish', 'francesmcdormand', 'francisco', 'francisfordcoppola', 'frank', 'frankenstein', 'frankgrillo', 'franki', 'frankiefaison', 'frankiemuniz', 'franklangella', 'frankoz', 'frankwelk', 'frankwhaley', 'frantic', 'fratern', 'fraud', 'freak', 'fred', 'fredarmisen', 'freddi', 'freddiehighmor', 'freddieprinzejr', 'fr

In [ ]:
# Now, we can see that the Stemming has been done by using Porter Stemmer

# **Similarity Score - using Cosine Score**

This is becasue we are focussed on calculating the angle between the vectors (Cosine Distance) and not on their tip-to-tip distance (Euclidean Distance) for accurately measuring the similarity.

Euclidean Distance fails for high dimensional data.

The smaller the angle in cosine distance, the more it is similar.

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
cosine_similarity(vectors).shape

(4806, 4806)

In [ ]:
similarity = cosine_similarity(vectors)

# SImilarity Matrix

In [ ]:
similarity[0].shape

(4806,)

In [ ]:
similarity[1]

array([0.06593805, 1.        , 0.07476672, ..., 0.02106314, 0.        ,
       0.02248469])

In [ ]:
# Logic building

new_df['title'] == 'Avatar'

0        True
1       False
2       False
3       False
4       False
        ...
4804    False
4805    False
4806    False
4807    False
4808    False
Name: title, Length: 4806, dtype: bool

In [ ]:
new_df[new_df['title'] == 'Avatar']

   movie_id   title                                               tags
0     19995  Avatar  in the 22nd century, a parapleg marin is dispa...

In [ ]:
new_df[new_df['title'] == 'Avatar'].index

Index([0], dtype='int64')

In [ ]:
new_df[new_df['title'] == 'Avatar'].index[0]

np.int64(0)

In [ ]:
def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    # tells the index of the movie based on the movie name
    distances = similarity[movie_index]
    # tells the distances between movie vectors of the give movie index
    movies_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
    '''sorts the distance in descending order and selects the 5 most closest (similar) movie, it gives the output of the form
     [(index, distance1), (index, distance2), (index, distance3), (index, distance4), (index, distance5)], eg., [(1, 1.0000), (814, 0.20500), (519, 0.18500), (2311, 0.15960),(4804, 0.11583)
    '''
    for i in movies_list:
        print(new_df.iloc[i[0]].title)
        # prints the title of the movies based on the index while fetching it from the new_df

In [ ]:
recommend('Avatar')

Aliens vs Predator: Requiem
Battle: Los Angeles
Predator
Independence Day
Titan A.E.

In [ ]:
recommend('Batman')

Batman
Batman & Robin
Batman Returns
The R.M.
Batman

In [ ]:
new_df['title'].values

array(['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre',
       ..., 'Signed, Sealed, Delivered', 'Shanghai Calling',
       'My Date with Drew'], dtype=object)

# **Pickling**

In [ ]:
import pickle

In [ ]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bond’ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."

In [ ]:
pickle.dump(new_df.to_dict(),open('movie_dict.pkl','wb'))

In [ ]:
pickle.dump(similarity,open('similarity.pkl','wb'))